# Generated by Django 3.0.6 on 2023-04-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='title',
            field=models.TextField(default='null'),
        ),
    ]
