# Generated by Django 3.0.6 on 2023-04-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230426_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
